Implement quick fixes
unifiedjs/unified-language-server pull request #17
Opened 2021-12-29 13:48 UTC by remcohaszing

### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

This implements manual quick by replacing the reported range with values taken from the `expected` array on vfile messages.

2021-12-29 13:51 UTC, remcohaszing commented
I tested this manually in VS Code. It works pretty well. I wanted to add a screencast, but my screencast tool is broken. :(

2021-12-29 15:12 UTC, wooorm requested changes
Code looks good. At some point it might be good to start documenting what is supported?

2021-12-29 15:12 UTC, wooorm approved these changes
Code looks good. At some point it might be good to start documenting what is supported?

2021-12-29 15:21 UTC, remcohaszing commented
> Code looks good. At some point it might be good to start documenting what is supported?

That is documented, but it wasn’t updated in this PR! I’ll add it right now.

2021-12-29 16:33 UTC, wooorm approved these changes

2021-12-30 10:43 UTC, merged

2021-12-30 10:46 UTC, wooorm commented
Released!